// <auto-generated />
using System;
using Friable_mongo.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Friable_mongo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230405173328_cascade_link_identification")]
    partial class cascade_link_identification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Friable_mongo.InfoModels.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Friable_mongo.InfoModels.CollectionMark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdentificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Media")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdentificationId");

                    b.ToTable("CollectionMarks");
                });

            modelBuilder.Entity("Friable_mongo.InfoModels.Date", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Media")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dates");
                });

            modelBuilder.Entity("Friable_mongo.InfoModels.Identification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Bottom")
                        .HasColumnType("int");

                    b.Property<Guid?>("DateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Framed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InvetoryNumber")
                        .HasColumnType("int");

                    b.Property<int?>("Left")
                        .HasColumnType("int");

                    b.Property<string>("MaterialsSerialized")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegistrationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Right")
                        .HasColumnType("int");

                    b.Property<Guid?>("SignatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Support")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechniquesSerialized")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleDutch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleFrench")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Top")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("DateId");

                    b.HasIndex("RegistrationID")
                        .IsUnique();

                    b.HasIndex("SignatureId");

                    b.ToTable("Identifications");
                });

            modelBuilder.Entity("Friable_mongo.InfoModels.Inscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdentificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Media")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdentificationId");

                    b.ToTable("Inscriptions");
                });

            modelBuilder.Entity("Friable_mongo.InfoModels.Mounting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Assemblage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DamageSerialized")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneralCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MyProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surface")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Mountings");
                });

            modelBuilder.Entity("Friable_mongo.InfoModels.Pictorial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DamageSerialized")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fixative")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FriableMediaSerialized")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneralCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherMediaSerialized")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemarksCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemarksDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surface")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechniquesSerialized")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pictorials");
                });

            modelBuilder.Entity("Friable_mongo.InfoModels.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Function")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MountingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PrimarySupportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SecondarySupportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StorageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MountingId");

                    b.HasIndex("PrimarySupportId");

                    b.HasIndex("SecondarySupportId");

                    b.HasIndex("StorageId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("Friable_mongo.InfoModels.Signature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Media")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Signatures");
                });

            modelBuilder.Entity("Friable_mongo.InfoModels.Storage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationNumber")
                        .HasColumnType("int");

                    b.Property<string>("MaterialSerialized")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Storages");
                });

            modelBuilder.Entity("Friable_mongo.InfoModels.Support", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Assemblage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DamageSerialized")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneralCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialSerialized")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaperType1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaperType2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaperType3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PictorialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Pinholed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RectoVerso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemarksCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemarksDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surface")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Watermark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WatermarkDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WatermarkLocation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PictorialId");

                    b.ToTable("Supports");
                });

            modelBuilder.Entity("Friable_mongo.InfoModels.CollectionMark", b =>
                {
                    b.HasOne("Friable_mongo.InfoModels.Identification", null)
                        .WithMany("CollectionMarks")
                        .HasForeignKey("IdentificationId");
                });

            modelBuilder.Entity("Friable_mongo.InfoModels.Identification", b =>
                {
                    b.HasOne("Friable_mongo.InfoModels.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId");

                    b.HasOne("Friable_mongo.InfoModels.Date", "Date")
                        .WithMany()
                        .HasForeignKey("DateId");

                    b.HasOne("Friable_mongo.InfoModels.Registration", "Registration")
                        .WithOne("Identification")
                        .HasForeignKey("Friable_mongo.InfoModels.Identification", "RegistrationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Friable_mongo.InfoModels.Signature", "Signature")
                        .WithMany()
                        .HasForeignKey("SignatureId");

                    b.Navigation("Artist");

                    b.Navigation("Date");

                    b.Navigation("Registration");

                    b.Navigation("Signature");
                });

            modelBuilder.Entity("Friable_mongo.InfoModels.Inscription", b =>
                {
                    b.HasOne("Friable_mongo.InfoModels.Identification", null)
                        .WithMany("Inscriptions")
                        .HasForeignKey("IdentificationId");
                });

            modelBuilder.Entity("Friable_mongo.InfoModels.Registration", b =>
                {
                    b.HasOne("Friable_mongo.InfoModels.Mounting", "Mounting")
                        .WithMany()
                        .HasForeignKey("MountingId");

                    b.HasOne("Friable_mongo.InfoModels.Support", "PrimarySupport")
                        .WithMany()
                        .HasForeignKey("PrimarySupportId");

                    b.HasOne("Friable_mongo.InfoModels.Support", "SecondarySupport")
                        .WithMany()
                        .HasForeignKey("SecondarySupportId");

                    b.HasOne("Friable_mongo.InfoModels.Storage", "Storage")
                        .WithMany()
                        .HasForeignKey("StorageId");

                    b.Navigation("Mounting");

                    b.Navigation("PrimarySupport");

                    b.Navigation("SecondarySupport");

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("Friable_mongo.InfoModels.Support", b =>
                {
                    b.HasOne("Friable_mongo.InfoModels.Pictorial", "Pictorial")
                        .WithMany()
                        .HasForeignKey("PictorialId");

                    b.Navigation("Pictorial");
                });

            modelBuilder.Entity("Friable_mongo.InfoModels.Identification", b =>
                {
                    b.Navigation("CollectionMarks");

                    b.Navigation("Inscriptions");
                });

            modelBuilder.Entity("Friable_mongo.InfoModels.Registration", b =>
                {
                    b.Navigation("Identification");
                });
#pragma warning restore 612, 618
        }
    }
}
